# Generated by Django 5.2.1 on 2025-05-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('types', models.CharField(choices=[('Tech', 'Tech'), ('Non Tech ', 'Non Tech'), ('Others', 'Others')], max_length=200)),
            ],
        ),
    ]
