# Generated by Django 5.2.1 on 2025-05-22 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empolyee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('about', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('Manager', 'manager'), ('Project Lead', 'pl'), ('Software Developer', 'sd')], max_length=20)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
