# Generated by Django 5.2.1 on 2025-05-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_empolyee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empolyee',
            name='id',
        ),
        migrations.AddField(
            model_name='empolyee',
            name='employee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empolyee',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
